services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - ./frontend/webapp:/app
    - /app/node_modules
    ports:
    - 3000:3000
    networks:
    - job-search-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5001:5000
    networks:
      - job-search-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - 9200:9200
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - job-search-network

  metabase:
    container_name: metabase
    image: metabase/metabase
    ports:
      - 3001:3000
    volumes:
      - /metabase
    networks:
      - job-search-network
  
  mongodb-primary:
    image: docker.io/bitnami/mongodb:7.0
    hostname: mongodb-primary
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - /bitnami/mongodb
    ports:
      - 27017:27017
    networks:
      - job-search-network


networks:
  job-search-network:
    name: job-search-network
